CREATE TABLE `actor_hero` (
  `actorid` int(11) NOT NULL DEFAULT 0 COMMENT '所属角色id',
  `offset` smallint(6) NOT NULL DEFAULT 0 COMMENT '位置索引',
  `herokind` smallint(6) NOT NULL DEFAULT 0 COMMENT '英雄种类',
  `name` varbinary(22) NOT NULL DEFAULT '' COMMENT '英雄名称',
  `shape` smallint(6) NOT NULL DEFAULT 0 COMMENT '英雄形象',
  `level` smallint(6) NOT NULL DEFAULT 0 COMMENT '等级',
  `experience` bigint(20) NOT NULL DEFAULT 0 COMMENT '经验',
  `feats` smallint(6) NOT NULL DEFAULT 0 COMMENT '功勋',
  `official` tinyint(4) NOT NULL DEFAULT 0 COMMENT '官职',
  `mastership` int(11) NOT NULL DEFAULT 0 COMMENT '统帅(所能统率部队的数量上限)',
  `health` tinyint(4) NOT NULL DEFAULT 0 COMMENT '健康',
  `grade` tinyint(4) NOT NULL DEFAULT 0 COMMENT '进阶',
  `state` tinyint(4) NOT NULL DEFAULT 0 COMMENT '状态',
  `attack` smallint(6) NOT NULL DEFAULT 0 COMMENT '攻击',
  `defance` smallint(6) NOT NULL DEFAULT 0 COMMENT '防御',
  `agility` smallint(6) NOT NULL DEFAULT 0 COMMENT '敏捷',
  `hp` smallint(6) NOT NULL DEFAULT 0 COMMENT '生命',
  `skill0` smallint(6) NOT NULL DEFAULT 0 COMMENT '技能',
  `skill1` smallint(6) NOT NULL DEFAULT 0 COMMENT '技能',
  `skill2` smallint(6) NOT NULL DEFAULT 0 COMMENT '技能',
  `skill3` smallint(6) NOT NULL DEFAULT 0 COMMENT '技能',
  KEY (`actorid`)
) ENGINE=MyISAM;
